site_name: Kasal Documentation
site_description: Documentation for the Kasal application
site_author: Kasal Team
repo_url: https://github.com/yourusername/kasal
repo_name: kasal

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
    - grid
  icon:
    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_if_no_docstring: false
  - git-revision-date-localized:
      type: date

nav:
  - Home: index.md
  - Getting Started:
    - Installation: GETTING_STARTED.md
    - Best Practices: BEST_PRACTICES.md
  - Architecture:
    - Overview: ARCHITECTURE.md
    - Authorization: AUTHORIZATION.md
    - Repository Pattern: REPOSITORY_PATTERN.md
    - Database:
      - Migrations: DATABASE_MIGRATIONS.md
      - Seeding: DATABASE_SEEDING.md
    - Models: MODELS.md
    - Schemas: 
      - Overview: SCHEMAS.md
      - Structure: SCHEMAS_STRUCTURE.md
  - Features:
    - Generation Features: generation.md
    - CrewAI Engine: CREWAI_ENGINE.md
    - LLM Manager: LLM_MANAGER.md
    - Logging: LOGGING.md
    - Workflows: workflow.md
    - Tasks: task.md
    - Jobs: job.md
    - Flows: flows.md
    - Agents: agents.md
    - Crew: crew.md
  - Development:
    - Zustand State Management: zustand.md
    - Node Decorators: nodeDecorator.md
    - Shortcuts: shortcuts.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/kasal
  generator: false

extra_css:
  - css/extra.css

copyright: Copyright &copy; 2025 Kasal Team 